Create social media folder and files
cabinetoffice/gsg-guidance pull request #6
Opened 2021-01-22 10:05 UTC by TechPunk316

2021-01-22 11:32 UTC, jonodrew commented
Is this a review of the content? There are some places where the phrasing feels a little awkward. Will there be a separate second-eye process?

2021-01-22 11:41 UTC, TechPunk316 commented
I will have a look over this in the Google Docs and get it 2i'd by another tech writer. Was just having a play to see check the layout.

2021-09-01 17:00 UTC, jonodrew requested changes

2021-09-01 17:00 UTC, jonodrew commented on source/social-media-guidance/using-social-media-securely/index.html.md.erb
> +Note: Never store passwords in files that are not password protected, or in shared, unencrypted documents on servers.
This repeats content above - is it necessary to do so?

2021-09-06 11:41 UTC, jonodrew commented on source/social-media-guidance/perform-social-media-security-assessment/index.html.md.erb
> +```yaml
@TechPunk316 you've kept the code blocks rather than using the quote markdown I've used above. Is the code style more common? It feels very unwieldy, because it doesn't wrap the content at all.

2021-09-06 11:56 UTC, TechPunk316 commented on source/social-media-guidance/index.html.md.erb
> +[Placeholder content]
Ok, I will add something

2021-09-06 11:58 UTC, TechPunk316 commented on source/social-media-guidance/using-social-media-securely/index.html.md.erb
> +Note: Never store passwords in files that are not password protected, or in shared, unencrypted documents on servers.
Is this is reference to the note? I think it's fine to leave it as it's a big problem and a reminder won't do any harm.

2021-09-06 12:05 UTC, jonodrew commented on source/social-media-guidance/using-social-media-securely/index.html.md.erb
> +Note: Never store passwords in files that are not password protected, or in shared, unencrypted documents on servers.
It is - but I meant more whether we can move content to a different file where it's the same to make sure any changes are reflected everywhere. More of an engineering question than a content one I think, so this can be resolved

2021-09-06 12:11 UTC, TechPunk316 commented on source/social-media-guidance/perform-social-media-security-assessment/index.html.md.erb
> +```yaml
It wasn't showing any changes you made. I just deleted the yaml bit where I could so it was in line with what was here - https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Happy for it to be changed to the correct thing.

2021-09-06 12:13 UTC, TechPunk316 reviewed
Is it better to start a fresh pull request? This is starting to get a little confusing

2021-09-06 12:14 UTC, jonodrew commented
> Is it better to start a fresh pull request? This is starting to get a little confusing

sure, if you'd like!

2021-09-06 13:05 UTC, jonodrew commented
Yeah, I think the quotes look better. Here's a comparison
![Screenshot 2021-09-06 at 14 02 32](https://user-images.githubusercontent.com/3410350/132221812-895cdc95-75fb-41d6-8c97-a5efd65c8acf.png)
^^ quote
![Screenshot 2021-09-06 at 14 03 33](https://user-images.githubusercontent.com/3410350/132221805-e03204d0-f462-4091-8d4f-799289704266.png)
^^ backticks

If you agree can you change the other areas where you've used backticks to indicate something important to a reader?

2021-09-06 13:44 UTC, TechPunk316 commented
Yup, will do

2021-09-06 14:19 UTC, jonodrew approved these changes

2021-09-06 14:19 UTC, merged